name: Promote global repositories version automaticaly

on:
    repository_dispatch:
        types: [ promote ]

jobs:
    promote-main:
        uses: ./.github/workflows/promote-reuse.yml
        with:
            branch: main
            node-version: 14.x
        secrets: inherit
    promote-stage:
        uses: ./.github/workflows/promote-reuse.yml
        with:
            branch: stage
            node-version: 14.x
        secrets: inherit
